### ISSUE TITLE
容器高度固定才可正常显示吗?

### ISSUE THREAD

**Issue by imal1** [SHISME/react-native-draggable-grid#1]
如题, 如何设置容器弹性高度

**Comment by SHISME** [comment]
> 如题, 如何设置容器弹性高度

grid 的 style 默认是 [flex:1],所以需要外面包裹的那一层是有高度和宽度的，能给个例子你具体想要怎样的效果吗

**Comment by imal1** [comment]
> > 如题, 如何设置容器弹性高度
> 
> grid 的 style 默认是 [flex:1],所以需要外面包裹的那一层是有高度和宽度的，能给个例子你具体想要怎样的效果吗

具体就是一个antd-mobile-rn组件库中一个弹性的Modal框, 容器就做在Modal框里. 设置容器宽高的话,受控的grid数量可能无法填充,  现在我暂时根据grid的行数变化加载容器的高度, 但是毕竟不work,也很丑

**Comment by SHISME** [comment]
> > > 如题, 如何设置容器弹性高度
> > 
> > 
> > grid 的 style 默认是 [flex:1],所以需要外面包裹的那一层是有高度和宽度的，能给个例子你具体想要怎样的效果吗
> 
> 具体就是一个antd-mobile-rn组件库中一个弹性的Modal框, 容器就做在Modal框里. 设置容器宽高的话,受控的grid数量可能无法填充, 现在我暂时根据grid的行数变化加载容器的高度, 但是毕竟不work,也很丑

我的理解你大概是这样的吗
```
<Modal>
  <Grid />
</Modal>
```
这种情况，grid 的 container 默认 flex 也是 1，会铺满整个Modal，grid 里面item的宽度是根据grid的宽度和每行数量动态算出来的，高度的话没有动态计算，是用传入的item的高度来的
