### ISSUE TITLE
update in array gives error "unable to read x of undefined"

### ISSUE THREAD

**Issue by vamshi9666** [SHISME/react-native-draggable-grid#16]
I placed this component in render method with some initial array  and in ```componentDidMount``` I updated array in state.

**Comment by SHISME** [comment]
ok, i will check it

**Comment by vamshi9666** [comment]
its accepting state change of one object , but when I try to change more than one , 
![Screen Shot 2019-08-07 at 11 25 57 AM](https://user-images.githubusercontent.com/28837336/62598187-2b5d7c00-b906-11e9-9112-45496c09459d.png)

**Comment by vamshi9666** [comment]
I solved this. I was changing array structure before when I see this error. and then I also encountered other error ```currentPosition of undefined ``` on drag.then I realised datatype of updated array is different from originated array.
