### ISSUE TITLE
feature request : add prop to enable vibration on drag

### ISSUE THREAD

**Issue by Under-Warz** [SHISME/react-native-draggable-grid#17]
Hi @SHISME ,

is it possible to add a props to enable or not the mobile vibration on every position changed when dragging. I can make a PR if you don't have time to do it.

Thx,

**Comment by SHISME** [comment]
Vibration?

**Comment by Under-Warz** [comment]
@SHISME yes : https://facebook.github.io/react-native/docs/vibration

By exemple, every time the draged item make other item moved, we could trigger a small vibration (~200ms by exemple)

**Comment by SHISME** [comment]
> @SHISME yes : https://facebook.github.io/react-native/docs/vibration
> 
> By exemple, every time the draged item make other item moved, we could trigger a small vibration (~200ms by exemple)

i think maybe i can provide a event prop which trigger when other  draged item make other item moved, i think this maybe better

**Comment by Under-Warz** [comment]
@SHISME yes, even better ;)

**Comment by SHISME** [comment]
i had added onResetSort

**Comment by Under-Warz** [comment]
@SHISME nice ! thx for your reactivity
