### ISSUE TITLE
Disable dragging for certain blocks?

### ISSUE THREAD

**Issue by joshuakoh7** [SHISME/react-native-draggable-grid#23]
Trying to pad the empty space in an incomplete grid with filler blocks but don't want these to be dragged/sorted. Possible to add a prop to disable drag?

**Comment by SHISME** [comment]
ok，i will add props to support that

**Comment by SHISME** [comment]
I had add disabledDrag and disabledReSorted

**Comment by RanaAzwar** [comment]
please correct spelling in read me file (**disabledResorted**)in props its disabledReSorted.

**Comment by hexatown-haidar** [comment]
disbaledDrag prop not working........!

**Comment by SHISME** [comment]
> disbaledDrag prop not working........!

disabledDrag not disbaledDrag
@hexatown-haidar

**Comment by jhon-hst** [comment]
disabledDrag is no working  or please tell me what my mistake
`
const Render_item = ({ name, key }) => {
    return (
	    <View
		    style={[ styles.containerImage ]}
		    key={key}
		    disabledDrag={false}
		    disabledReSorted={false}
	    >
		    <Image source={Images['photo1']} style={[ styles.image ]} />
	    </View>
    )
}
return (
  <View style={styles.wrapper}>
	  <DraggableGrid
		  numColumns={2}
		  renderItem={Render_item}
		  data={images}
		  itemHeight={120}
		  onDragRelease={(data) => {
			  setImages(data)
		  }}
		  style={{ maxHeight: 350 }}
	  />
  </View>
)
`
