### ISSUE TITLE
bug on onDragRelease function 

### ISSUE THREAD

**Issue by AahilShahzad** [SHISME/react-native-draggable-grid#28]
using 
"react-native-draggable-grid": "^2.0.0",
"react": "16.8.1",
"react-native": "^0.61.3",

![Screenshot_1588680089](https://user-images.githubusercontent.com/13553516/81063900-1c861300-8ef2-11ea-841e-dad8e96952ab.png)

**Comment by AahilShahzad** [comment]
i am facing this issue onDragRelease function
and this function returns draged box data undefined

**Comment by SHISME** [comment]
Could you show me some core code?

**Comment by AahilShahzad** [comment]
here  is my code screenshots

<img width="731" alt="Screenshot 2020-05-11 at 4 15 33 PM" src="https://user-images.githubusercontent.com/13553516/81556208-5f893000-93a3-11ea-8369-7d4077591c24.png">
<img width="848" alt="Screenshot 2020-05-11 at 4 17 27 PM" src="https://user-images.githubusercontent.com/13553516/81556223-644de400-93a3-11ea-87c4-f9e5849f0925.png">

here is my console response

`start drag {"key": 10, "uri": "/var/mobile/Containers/Data/Application/B8C37563-B289-483E-BCD2-CCC54D7D3534/Library/Caches/RNRectangleScanner/C1589195470.jpeg"}`

`drag release [{"key": 13, "uri": "/var/mobile/Containers/Data/Application/B8C37563-B289-483E-BCD2-CCC54D7D3534/Library/Caches/RNRectangleScanner/O1589193443.jpeg"}, {"key": 45, "uri": "/var/mobile/Containers/Data/Application/B8C37563-B289-483E-BCD2-CCC54D7D3534/Library/Caches/RNRectangleScanner/O1589194344.jpeg"}, undefined, {"key": 10, "uri": "/var/mobile/Containers/Data/Application/B8C37563-B289-483E-BCD2-CCC54D7D3534/Library/Caches/RNRectangleScanner/C1589195470.jpeg"}]`

**Comment by SHISME** [comment]
https://github.com/SHISME/react-native-draggable-grid/commit/26dd482247d93754c71dfe412ee5f3753aadd824 i think maybe fixed it

**Comment by AahilShahzad** [comment]
i have updated version 
to
"version": "2.0.0",
from
"version": "2.1.2",
but have same issue

**Comment by projjwalg** [comment]
I am having this same issue.
anyone have any solution?

**Comment by projjwalg** [comment]
@AahilShahzad How did you solve your issue?
I am having the same problem.
Pleas suggest.

Thanks

**Comment by SHISME** [comment]
> @AahilShahzad How did you solve your issue?
> I am having the same problem.
> Pleas suggest.
> 
> Thanks

Have you remove item from the data before release drag?

**Comment by projjwalg** [comment]
> Have you remove item from the data before release drag?

No I have not removed item from data before release drag.

**Comment by projjwalg** [comment]
> @AahilShahzad How did you solve your issue?
> I am having the same problem.
> Please suggest.
> 
> Thanks


This issue occurs when we set an integer as the key instead of string.

**Comment by SHISME** [comment]
> > @AahilShahzad How did you solve your issue?
> > I am having the same problem.
> > Please suggest.
> > Thanks
> 
> This issue occurs when we set an integer as the key instead of string.

OK，i will fix it
