### ISSUE TITLE
Unable to have more than one grid component

### ISSUE THREAD

**Issue by garrettjoecox** [SHISME/react-native-draggable-grid#29]
This took me a while to debug as I thought it was an issue in my code, but it seems you are storing the passed in data prop in scoped variables:
```
const orderMap: {
  [itemKey: string]: IOrderMapItem
} = {}
const itemMap: {
  [itemKey: string]: any
} = {}
const items: IItem<any>[] = []
```

This is a pretty bad practice as far as react goes, and prevents you from being able to use this grid component more than once. Any plans on fixing this?

**Comment by SHISME** [comment]
Got it, I will fix it as soon as possible
