### ISSUE TITLE
Cannot delete more than one item from the center of the grid 

### ISSUE THREAD

**Issue by MrSamsa42** [SHISME/react-native-draggable-grid#3]
I have a simple implementation, that is structured much like the demo shown in the README.md.  That is, I have an array of objects stored in state, and my render method is simply the DraggableGrid component inside a View component.  The array of objects includes unique image urls and an integer key -- for example, the first object looks like this:
  { url: 'http://cdn-www.dailypuppy.com/dog-images/sydney-the-australian-cattle-dog-8_48158_2010-07-22_w450.jpg', key: 0 }

I tried to implement a delete method to remove the image when the user touches one of the photos in the grid.  Upon a deleting an image from the middle of the grid, the grid restructures as expected.  However, subsequent deletions fail, resulting in this error:

[12:30:41] TypeError: undefined is not an object (evaluating '_this.items[itemIndex].currentPosition')

This error is located at:
    in DraggableGrid (at App.js:62)
    in RCTView (at View.js:44)
    in MyTest (at registerRootComponent.js:17)
    in RootErrorBoundary (at registerRootComponent.js:16)
    in ExpoRootComponent (at renderApplication.js:34)
    in RCTView (at View.js:44)
    in RCTView (at View.js:44)
    in AppContainer (at renderApplication.js:33)
* components\draggable-grid\draggable-grid.tsx:379:26 in moveBlockToBlockOrderPosition
* components\draggable-grid\draggable-grid.tsx:100:45 in <unknown>
* components\draggable-grid\draggable-grid.tsx:96:27 in componentWillReceiveProps
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:8176:39 in callComponentWillReceiveProps
- node_modules\react-native\Libraries\Renderer\oss\ReactNativeRenderer-dev.js:8490:8 in updateClassInstance
- ... 16 more stack frames from framework internals

My delete implementation is as follows: 

```
  deletePhoto = (item) => {
    let pics = [...this.state.data];
    pics = pics.filter( (pic) => pic.url !== item.url);

    this.setState( (state) => ({data: pics}));
  }
```

**Comment by SHISME** [comment]
ok, i will check later

**Comment by SHISME** [comment]
sorry , i am busy recently, i will add feature to support delete more than one item on this weekend
