### ISSUE TITLE
any events doesn't work on android build 

### ISSUE THREAD

**Issue by GalushkoVasiliy** [SHISME/react-native-draggable-grid#32]
react-native android app

onLongPress, onPress, etc events doesn't work

**Comment by lohtiavip** [comment]
Hiii @GalushkoVasiliy , How you have solved it?

**Comment by GalushkoVasiliy** [comment]
hi, did you resolve your problem?

ср, 14 окт. 2020 г. в 07:31, lohtiavip <notifications@github.com>:

**Comment by lohtiavip** [comment]
yes , in my case when i wasn't give height to view then that time onLongPress, onPress was not working in android but working in ios
 <View style={{width: '90%', marginTop: 20}}>
                <DraggableGrid
                    numColumns={3}
                    renderItem={render_item}
                    data={list}
                    onItemPress={(item) => {
                        // if (item.disabledDrag === false) {
                        //
                        // } else {
                            setselectedIndex(item.name);
                            setisOpen(true);
                        // }
                    }}
                    onDragRelease={(data) => {
                        console.log(data);
                        setList(data);
                    }}
                />
            </View>

when i have give height to view, then onLongPress, onPress working fine android
<View style={{width: '90%', height:'90%',marginTop: 20}}>
                <DraggableGrid
                    numColumns={3}
                    renderItem={render_item}
                    data={list}
                    onItemPress={(item) => {
                        // if (item.disabledDrag === false) {
                        //
                        // } else {
                            setselectedIndex(item.name);
                            setisOpen(true);
                        // }
                    }}
                    onDragRelease={(data) => {
                        console.log(data);
                        setList(data);
                    }}
                />
            </View>

**Comment by GalushkoVasiliy** [comment]
👍🏻👍🏻👍🏻

Сб, 21 нояб. 2020 г. в 14:08, lohtiavip <notifications@github.com>:
