### ISSUE TITLE
disabledDrag is no working

### ISSUE THREAD

**Issue by jhon-hst** [SHISME/react-native-draggable-grid#49]
disabledDrag is no working or please tell me what my mistake
I need some specific boxes not to be draggable

        `const render_item = ({ name, key }) => {
               return (
                    <View
	                    style={[ styles.containerImage ]}
	                    key={key}
	                    disabledDrag={true}
	                    disabledReSorted={true}
                    >
	                    <Image source={Images['photo1']} style={[ styles.image ]} />
                    </View>
              )
        }

        return (
            <DraggableGrid
                  numColumns={2}
                  renderItem={render_item}
                  data={images}
                  itemHeight={120}
                  onDragRelease={(data) => {
                        setImages(data)
                  }}
                  style={{ maxHeight: 350 }}
            />
        )`

**Comment by SHISME** [comment]
you need set disabledDrag in your data, not in children's porps,
may like this

```

images = [
{
  disabledDrag: true,
  disabledReSorted: true

}
]
```

**Comment by jhon-hst** [comment]
Thank you very much, I solved the problem
