### ISSUE TITLE
How can i set the drag action without do a onLongPress? 

### ISSUE THREAD

**Issue by AFMW** [SHISME/react-native-draggable-grid#5]
Im looking for using the drag action when I do pressIn on each element, Is it possible?
by the way, Can i delete any element of the data just by take it out from the this.state.data prop, do that immediatly refresh the view?

**Comment by SHISME** [comment]
It can't drag action when pressIn, if you really want to do that, you can fork this repository and setActiveBlock when pressIn.
When you delete props data ,the view will refresh immediatly.
