### ISSUE TITLE
How to disable the dragging?

### ISSUE THREAD

**Issue by Ruzen1** [SHISME/react-native-draggable-grid#50]
Hey am trying to disable the dragging feature after some certain conditions.
Is is possible? Could anyone please guide me?

**Comment by SHISME** [comment]
You can set disabledDrag and disabledReSorted in the data like this 

```tsx
this.setState({
 data:[
 {
  disabledDrag: true,
  disabledReSorted: true,
},{
  disabledDrag: false,
  disabledReSorted: false,
 }
];

});
 render() {
    return (
      <View style={styles.wrapper}>
        <DraggableGrid
          numColumns={4}
          renderItem={this.render_item}
          data={this.state.data}
          onDragStart={this.onDragStart}
          dragStartAnimation={{
            transform:[
              {scale:this.state.animatedValue}
            ],
          }}
        />
      </View>
    );
  }



```
`disabledDrag:true` will let the item could not be drag,
`disabledReSorted: true` will ignore item when resorted data

**Comment by Ruzen1** [comment]
@SHISME WOW, thank you very much for your swift reply.Now I see, how to use that disabledDrag. I knew that would do the thing but was not sure how to use it.

It was so much nicer if there was any possibility to stop the whole grid at once.
Anyways this shall work for me, thank you very much. 

I have one other question, if you could please guide me. I thought it was css but it aint working.

Please look at this picture. Am using your library to drag. The book Facebook is actually being dragged but when I take it down, it seems as if it vanished. Anything from you is very hardly appreciated. Thank you.
`
 ![image-1d31e7ea-97af-4db3-958d-a895326de3ea](https://user-images.githubusercontent.com/25242058/122359637-b0009300-cf90-11eb-8122-23beb30ca649.jpg)

**Comment by SHISME** [comment]
> @SHISME WOW, thank you very much for your swift reply.Now I see, how to use that disabledDrag. I knew that would do the thing but was not sure how to use it.
> 
> It was so much nicer if there was any possibility to stop the whole grid at once.
> Anyways this shall work for me, thank you very much.
> 
> I have one other question, if you could please guide me. I thought it was css but it aint working.
> 
> Please look at this picture. Am using your library to drag. The book Facebook is actually being dragged but when I take it down, it seems as if it vanished. Anything from you is very hardly appreciated. Thank you.
> `
> ![image-1d31e7ea-97af-4db3-958d-a895326de3ea](https://user-images.githubusercontent.com/25242058/122359637-b0009300-cf90-11eb-8122-23beb30ca649.jpg)

i think maybe you should set itemHeight

```tsx
< DraggableGrid
  itemHeight={yourItemHeight}
>
</DraggableGrid>


```

**Comment by Ruzen1** [comment]
@SHISME Thank you for the advice.
But it didnt work . I tried creating a new view outside the grid view and set the height. It did solve the problem but if there are more items, the height doesnt go dynamic resulting in incomplete grid. :/

**Comment by Ruzen1** [comment]
@SHISME My bad, I solved it by setting minHeight to the device height in the view outside the grid view lol . Sorry for bothering you. 

By the way, sometimes when I just start to drag it , it gets stuck. It's really sometimes. Do you know the cause for it?
For example the below Toefel Test Book is stuck and cannot be dragged. However if i try again, its fine. 

![image-5f0ca519-ae3d-4a1b-98b5-0bbf34f9f098](https://user-images.githubusercontent.com/25242058/122633894-eb789a00-d115-11eb-93cc-cfc3f5802b64.jpg)

**Comment by Ruzen1** [comment]
I am closing the issue so that it be discussed somewhere other time.
