### ISSUE TITLE
Drag to bottom to delete feature?

### ISSUE THREAD

**Issue by ZijianZhang991203** [SHISME/react-native-draggable-grid#51]
First of all, thank you so much for developing such a nice library. 
Is it possible though to do this feature with this library? Any hints will be greatly appreciated.

**Comment by SHISME** [comment]
You can use onDragging to control when to delete item, i think user control when to delete is better

**Comment by ZijianZhang991203** [comment]
Thank you for the hint. Also, is it possible that I can add an nondraggable and nonsortable(meaning other grid cannot make it resort) grid. Like the add button for image in weChat with this library?
