### ISSUE TITLE
Cannot read property 'currentPosition' of undefined

### ISSUE THREAD

**Issue by AFMW** [SHISME/react-native-draggable-grid#6]
Im trying to add some photos to the data I'm showing but  when I already added them and try to drag an item it throws that error.
Im using ImagePicker for uploading the items // https://github.com/ivpusic/react-native-image-crop-picker

I do a setState.. statement for setting for updating the data into the view
My this.state.data before adding the new items:
data:[{image:'http://www.alexander-anderson.com/wp-content/uploads/2018/11/homepage-tiles_new-construction.jpg',key:0}]

My this.state.data after adding the items:
data:[{image:"http://www.alexander-anderson.com/wp-content/uploads/2018/11/homepage-tiles_new-construction.jpg",key:0},
{image:"https://ubicala-users.s3.amazonaws.com/properties/u54135-11811/Apartamento-Venta--5821318-large.jpg",key:1},
{image:"https://ubicala-users.s3.amazonaws.com/properties/u54135-11811/Apartamento-Venta--7489622-large.jpg",key:2}]

This is a screenshot of that issue:
![Simulator Screen Shot - iPhone 6s - 2019-04-01 at 11 21 11](https://user-images.githubusercontent.com/26683460/55343240-50317680-5470-11e9-9824-174e658f7e40.png)

**Comment by SHISME** [comment]
what version did you use？

**Comment by AFMW** [comment]
> what version did you use？

i have the 1.0.8 version

**Comment by SHISME** [comment]
sorry, i can't reappear your problem，could you show me your pivotal code，and how you found the problem?

**Comment by AFMW** [comment]
@SHISME I solve it when I realize The key item in the data object wasnt done in the correct way.

**Comment by Killua-Zhuang** [comment]
I meet the same problem, would you mind sharing your solution? @AFMW

**Comment by SHISME** [comment]
> I meet the same problem, would you mind sharing your solution? @AFMW

You need keep your data have unique key

**Comment by Killua-Zhuang** [comment]
> > I meet the same problem, would you mind sharing your solution? @AFMW
> 
> You need keep your data have unique key

I'm sure the key is unique, I use the index as the key. Finally……I just rebuild this project without changes, then the problem is fixed.∠( ᐛ 」∠)＿
