### ISSUE TITLE
Typescript error in block.tsx

### ISSUE THREAD

**Issue by alzalabany** [SHISME/react-native-draggable-grid#73]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `react-native-draggable-grid@2.1.6` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/react-native-draggable-grid/src/block.tsx b/node_modules/react-native-draggable-grid/src/block.tsx
index 25e4694..6b2927f 100644
--- a/node_modules/react-native-draggable-grid/src/block.tsx
+++ b/node_modules/react-native-draggable-grid/src/block.tsx
@@ -17,6 +17,7 @@ interface BlockProps {
   onLongPress: () => void
   panHandlers: GestureResponderHandlers
   delayLongPress:number
+  children?:React.ReactNode
 }
 
 export const Block: FunctionComponent<BlockProps> = ({
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by SHISME** [comment]
OK, I had fixed it.
