### ISSUE TITLE
Does this work within a ScrollView?

### ISSUE THREAD

**Issue by DVassilev** [SHISME/react-native-draggable-grid#8]
Curious if it's possible to use this in conjunction with a ScrollView for content that overflows? If so, any examples? Thanks!

**Comment by devsrv** [comment]
whenever I wrap with ScrollView, all the draggable items fly away

**Comment by Killua-Zhuang** [comment]
@SHISME 我想把这个组件放在一个水平的scrollview里面 限制高度 使其可以横向滚动以看到所有的item 但是放到水平的scroll view里面的所有item都会完全重叠在第一个item的位置 检查元素发现每个item的 left都是0 （放在普通的View就是正常的 没有这种情况）
